consumes: 
  - application/json
definitions:
  UserLoginRequest:
    type: object
    properties: 
      email:
        type: string
      password: 
        type: string

  AccessToken: 
    type: object
    properties:
      AccessToken:
        type: string
      UserId:
        type: integer
        format: int
      TokenExpirations: 
        type: integer
        format: int

  RestErr:
    type: object
    properties: 
      message: 
        type: string
      status:
        type: integer
        format: int
      error: 
        type: string
info: 
  description: Flash cards learning platform Auth API 
  title: Moku Moku Auth API 
  version: 0.1.0
paths:
  /oauth/login:
    post: 
      tags: 
        - login
      operationId: userLogin
      description: Logs in a user 
      parameters:
        - name: user_login_data
          in: body
          required: true
          schema: 
            $ref: "#/definitions/UserLoginRequest"
      responses: 
        '200':
          description: User Logged in
          schema: 
            $ref: "#/definitions/AccessToken"
        default: 
          description: Error 
          schema: 
            $ref: "#/definitions/RestErr"

produces: 
  - application/json

schemes: 
  - http
  - https

swagger: "2.0"      